services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=clicks_user
      - POSTGRES_PASSWORD=clicks_password
      - POSTGRES_DB=clicks_db
      - REST_HOST=0.0.0.0
      - REST_PORT=8080
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - clicks-network

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clicks_user
      - POSTGRES_PASSWORD=clicks_password
      - POSTGRES_DB=clicks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clicks_user -d clicks_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - clicks-network

networks:
  clicks-network:
    driver: bridge

volumes:
  postgres_data:
